### ISSUE TITLE
ErrorException with Laravel 5.6.24

### ISSUE THREAD

**Issue by unkndono** [njbarrett/laravel-postgis#98]
Laravel version : 5.6.24
Postgis version : ^3.3

Can't use package because of this error : 
ErrorException: Declaration of Bosnadev\Database\Schema\Blueprint::point($column) should be compatible with Illuminate\Database\Schema\Blueprint::point($column, $srid = NULL)

**Comment by njbarrett** [comment]
Hi, thanks for reporting the issue.
I can see it is related to the dependecy package for which you have already opened a pull request to fix: https://github.com/bosnadev/database/pull/34

We will see if the maintainer merges it, otherwise I may need to remove that package as a dependency and roll it myself.

**Comment by unkndono** [comment]
Thank you :)

**Comment by luizguilhermefr** [comment]
@njbarrett The PR was merged. Would you tag the library update? :smile:

**Comment by njbarrett** [comment]
@luizguilhermefr I have tagged a new release 3.3.2. Thanks.
